# This file is a template, and might need editing before it works on your project.
# use docker image with latex preinstalled
# since there is no official latex image, use https://github.com/blang/latex-docker
# possible alternative: https://github.com/natlownes/docker-latex

stages:
  - test
  - release

before_script:
  - apt update -yqq
  - apt install -yqq npm
  - npm install

test:
  stage: test
  image: ubuntu:bionic
  script:
    - apt install -yqq chktex
    - npm test

deploy:
  stage: release
  image: blang/latex
  only:
    - master
    - develop
  script:
    - npm run build
  artifacts:
    paths:
      - "*.pdf"
    expire_in: 1 year

publish:
  stage: release
  image: node:12
  script:
    - npx semantic-release

